default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 10

development:
  <<: *default
  database: <%= ENV['DB_D_NAME'] %>
  host: <%= ENV['DB_D_HOST'] %>
  username: <%= ENV['DB_D_USERNAME'] %>
  password: <%= ENV['DB_D_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

test:
  <<: *default
  database: <%= ENV['DB_T_NAME'] %>
  host: <%= ENV['DB_T_HOST'] %>
  username: <%= ENV['DB_T_USERNAME'] %>
  password: <%= ENV['DB_T_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
