# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: ja
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
locales: [en, zh]
## Reporting locale, default: en. Available: en, ru.
internal_locale: ja

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    ## Default:
    # - config/locales/%{locale}.yml
    ## More files:
    - config/locales/**/*%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    ## For example, write devise and simple form keys to their respective files:
    # - ['{devise, simple_form}.*', 'config/locales/\1.%{locale}.yml']
    ## Catch-all default:
    - config/locales/%{locale}.yml

  # External locale data (e.g. gems).
  # This data is not considered unused and is never written to.
  external:
    ## Example (replace %#= with %=):
    # - "<%#= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: conservative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  # paths:
  #  - app/

  ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  # strict: true

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Translation Services
translation:
  google_translate_api_key: AIzaSyAfNXpt928py8cqNQZYY5RAN1s__7mUOkQ
#   # Google Translate
#   google_translate_api_key: "AbC-dEf5"
#   # DeepL Pro Translate
#   # Get an API key and subscription at https://www.deepl.com/pro to use DeepL Pro
#   deepl_api_key: "48E92789-57A3-466A-9959-1A1A1A1A1A1A"

## Do not consider these keys missing:
ignore_missing:
- 'activerecord.attributes.course.{faicon}'
- 'activerecord.attributes.equipment.{faicon}'
- 'activerecord.attributes.lecture.{faicon}'
- 'activerecord.attributes.lecture/work_kind.{faicon}'
- 'activerecord.attributes.lecture_staff.{faicon}'
- 'activerecord.attributes.lecture_student.{faicon}'
- 'activerecord.attributes.reserve.{faicon}'
- 'activerecord.attributes.role.{faicon}'
- 'activerecord.attributes.room.{faicon}'
- 'activerecord.attributes.room_group.{faicon}'
- 'activerecord.attributes.staff.{faicon}'
- 'activerecord.attributes.staff_wage.{faicon}'
- 'activerecord.attributes.student.{faicon}'
- 'activerecord.attributes.student_point.{faicon}'
- 'activerecord.attributes.subject.{faicon}'
- 'activerecord.attributes.subject_type.{faicon}'
- 'activerecord.attributes.user.{faicon}'
- 'activerecord.attributes.work_kind.{faicon}'
- 'activerecord.model.*'
- 'attributes.{faicon}'
# - '*.{faicon}'


# - 'errors.messages.{accepted,blank,invalid,too_short,too_long}'
# - '{devise}.*'

## Consider these keys used:
ignore_unused:
- 'activerecord.{attributes,models,errors}.*'
- 'attributes.*' # common in activerecord
- '{devise,ransack,validates_timeliness,cocoon}.*'
- 'kaminari.*' # kaminari
- 'helpers.page_entries_info.*' # kaminari
- 'enums.*' # enum_help
- 'flash.*' # responder
- 'helpers.{flash,select,submit,button}.*' # helpers
- 'errors.*' # validations
- 'simple_form.{yes,no}'
- 'simple_form.{placeholders,hints,labels}.*'
- 'simple_form.{error_notification,required}.:'
# units
- 'date.*'
- 'datetime.*'
- 'time.*'
- 'support.*'
- 'number.*'
- 'credit_types'

## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Exclude these keys from the `i18n-tasks check-consistent-interpolations` report:
ignore_inconsistent_interpolations:
- 'activerecord.attributes.*'

## Ignore these keys completely:
ignore:
  - kaminari.*

## Sometimes, it isn't possible for i18n-tasks to match the key correctly,
## e.g. in case of a relative key defined in a helper method.
## In these cases you can use the built-in PatternMapper to map patterns to keys, e.g.:
#
# <%# I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#       only: %w(*.html.haml *.html.slim),
#       patterns: [['= title\b', '.page_title']] %>
#
# The PatternMapper can also match key literals via a special %{key} interpolation, e.g.:
#
# <%# I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#       patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>


<% require './lib/i18n/csv_tasks' %>
# 一括出力・取込用タスク
# https://github.com/glebm/i18n-tasks/wiki/Custom-CSV-import-and-export-tasks
csv:
  export:
    # - ["faqs.*", "tmp/i18n-export/faqs.csv"]
    - "db/i18n-export/i18n.csv"
  import:
    - tmp/i18n-export/i18n.csv
    - tmp/i18n-export/faqs.csv